### ISSUE TITLE
Create DotNetProjectFile.Analyzers.SDK package 

### ISSUE THREAD

**Issue by Corniel** [dotnet-project-file-analyzers/dotnet-project-file-analyzers#154]
Currently, .NET project file analyzers does greatly (at least, I think) for project files bound to a single project. It is - however - still a bit cumbersome to validate files that don't. This is due to the fact that we can only hook up to build events that are - by design - bound to projects.

Therefore, currently, shared `.props` files are analyzed (and potentially reported) per project. Not ideal, to say the least. But I think there is a nice way - at least I think - to solve this. We can create a *empty* project file (at the same level as the `.sln`) that contains all shared files that we want to have analyzed. Something like this:

``` XML
<Project Sdk="DotNetProjectFile.Analyzers.Sdk">

  <ItemGroup>
    <AdditionalFiles Include=".editorconfig" />
    <AdditionalFiles Include=".github/**" />
    <AdditionalFiles Include="props/**" />
  </ItemGroup>
  
</Project>
```

The magic can be achieved by creating an own SDK that provides some nice alternative behavior:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <!-- Build something to trigger the anlyzers and prevent the output from showing up in your solution
  directory. Other options might be better.  -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>$([System.IO.Path]::GetTempPath())/.net/bin</OutputPath>
    <IntermediateOutputPath>$([System.IO.Path]::GetTempPath())/.net/obj</IntermediateOutputPath>
  </PropertyGroup>

  <!-- Ensure our analyzers are available -->
  <ItemGroup>
    <PackageReference Include="DotNetProjectFile.Analyzers" Version="*" PrivateAssets="all" />
  </ItemGroup>

  <!-- We should start with an empty project -->
  <ItemGroup>
    <Compile Remove="**" />
    <EmbeddedResource Remove="**" />
    <None Remove="**" />
  </ItemGroup>

</Project>
````

Microsoft has provided nice examples to get even more inspired: https://github.com/microsoft/MSBuildSdks/tree/main/samples

**Comment by CptWesley** [comment]
I really hope we can find an alternative, less invasive way. I already detest the AdditionalFile requirement for the analyzer to properly work.
