### ISSUE TITLE
FP Proj0200 & Proj0400: When <IsTestProject> is true is should be obvious

### ISSUE THREAD

**Issue by Corniel** [dotnet-project-file-analyzers/dotnet-project-file-analyzers#168]
If `<IsTestProject>true</IsTestProject>` it should be obvious that the project is packable, nor publishable.

**Comment by CptWesley** [comment]
As long as that means you should put them to `false`, I'm all on-board. Since the default is `true`.

**Comment by Corniel** [comment]
I'm not sure that I understand your remark? My idea is that, if the `<IsTestProject>true</IsTestProject>` is explictly set, than Proj0200 and Proj0400 should not report, but that does not mean that `<IsTestProject>` should always been set (true or false).

**Comment by CptWesley** [comment]
`Proj0200` and `Proj0400` maybe shouldn't be reporting, but we should have another rule that tells you to push `IsPackable` and `IsPublishable` to `false`, since their defaults are `true`.
