### ISSUE TITLE
Rule PROJ2100 triggers on <BR/> tags in .resx files

### ISSUE THREAD

**Issue by Gemberkoekje** [dotnet-project-file-analyzers/dotnet-project-file-analyzers#214]
The following code in a RESX:
``  
  <data name="LoremIpsumText" xml:space="preserve">
    <value>Lorem ipsum dolor sit amet.<br /><br /></value>
  </data>
``

Results in the PROJ2100 warning:
The element <br> has not been properly indented. ([external_roslyn:Proj2100](https://sonarcloud.io/organizations/tjip/rules#rule_key=external_roslyn%3AProj2100)  )

I think this is in error, as it's part of the value and shouldn't have any forced change in indenting.

**Comment by Corniel** [comment]
That is an interesting one! I agree that it should not report on nodes that are children of `<data>`. It also shows the need for an extra rule: `<data>` should only contain (HTML escaped) nodes and/or `<[CDATA[`.
