### ISSUE TITLE
NuGetAudit is broken in .NET 7

### ISSUE THREAD

**Issue by cremor** [dotnet-project-file-analyzers/dotnet-project-file-analyzers#93]
This is about [Proj0004: Run NuGet security audits automatically](https://dotnet-project-file-analyzers.github.io/rules/Proj0004.html)

The example explicitly shows to enable this for .NET 7. But according to https://github.com/NuGet/Home/issues/12730#issuecomment-1691307459 NuGetAudit is broken in .NET 7 and will stop working as soon as .NET SDK 7.0.401 ships. Only .NET 8 will have support for it.

**Comment by Corniel** [comment]
@cremor : You suggest to drop this rule?

**Comment by cremor** [comment]
The rule should only apply to .NET 8 projects. But since .NET 8 will enable NuGetAudit by default, only an explicitly disabled NuGetAudit will trigger it, and that might be unwanted. So maybe the rule isn't needed at all.

**Comment by Corniel** [comment]
@cremor I think that explicitly disabling it is a bad practice. So then this rule keeps some value. Thanks for reporting the issue.

**Comment by CptWesley** [comment]
@cremor I think that only running it when the .NET 8 SDK is used for building might result in flaky results for projects targeting older framework versions where not all developers have the same set of SDKs installed.

**Comment by Corniel** [comment]
I've adjusted the rule, to only report only when `<NuGetAudit>` is explicitly disabled.

**Comment by Corniel** [comment]
@cremor Just of curiosity, how did you find out about these analyzers?

**Comment by cremor** [comment]
I did a Google search for something and one of your rule pages on https://dotnet-project-file-analyzers.github.io was shown as a search result. I don't remember exactly what I searched but it could have been an analyzer package which is mentioned on https://dotnet-project-file-analyzers.github.io/rules/Proj1001.html (Btw, that page shows some broken links/markdown syntax.)
